# Generated by Django 5.0.4 on 2024-04-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='image',
            field=models.ImageField(null=True, upload_to='marca_imgs/'),
        ),
    ]
