# Generated by Django 5.0.4 on 2024-05-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_is_feat_caracterico_product_produto_em_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='marca_imgs/'),
        ),
    ]
