name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3]

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        dir  # Print current directory for debugging
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd env
        dir  # Print current directory for debugging
        Scripts\Activate
        cd..
        cd loja
        dir  # Print current directory for debugging
        python manage.py migrate
        python manage.py migrations
        python manage.py runserver
